/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAutomation: typeof import('./src/components/AddAutomation.vue')['default']
    AddCategory: typeof import('./src/components/AddCategory.vue')['default']
    AddTemplate: typeof import('./src/components/AddTemplate.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IncomeExpenseForm: typeof import('./src/components/IncomeExpenseForm.vue')['default']
    RecordList: typeof import('./src/components/RecordList.vue')['default']
    Report: typeof import('./src/components/Report.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
